### ISSUE TITLE
Containerize your web-app using vagga

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-DrEdi#9]
* [x] Learn about containers and related tools (LXC, Docker):
  * [x] https://www.youtube.com/watch?v=YFl2mCHdv24 **(great explanation!)**
  * [x] https://docs.docker.com/engine/tutorials/ (reference, borin')
  * [x] http://learningdocker.com/ (optional)
  * [x] https://hackr.io/tutorials/learn-docker (optional)
  * [x] http://internetdevels.ua/blog/docker-useful-links (bonus, additional info, tons of references)
  * [x] https://bunyk.wordpress.com/2015/07/22/docker-cheetsheet/ (refs, not needed for this task, way be useful in future in scope of #15)
* [x] Learn about vagga: [docs](https://vagga.readthedocs.io/), [repo](/tailhook/vagga)
* [x] Install vagga in your PC according to the [instructions in docs](https://vagga.readthedocs.io/en/latest/installation.html) (either as a deb package or via one-liner script)
* [x] Try building some simple Alpine Linux based vagga container, just to feel how it works
  * [x] Run some simple command like `bash` or `hostname` without specifying it in `commands` section
* [x] Create container for running your django app inside of it (there are some examples in vagga repo and docs)
  * [x] make PR with sqlite version (PR #19)
  * [x] make PR with postgresql in separate container (via `!Supervise`) (PR #21)
* [x] Move app testing into container in Travis CI (Ref: https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/.travis.yml)
  * [x] make PR (PR #24)

**Comment by DrEdi** [comment]
Start to learn how to add Pgsql.
Would it be better to create new branch or do it in the same as before?

**Comment by webknjaz** [comment]
sure, new branch per feature. here's an example: https://github.com/tailhook/vagga/blob/master/examples/tutorials/django/vagga.yaml#L98-L112

**Comment by webknjaz** [comment]
and here's an example of doing cross-container locks: https://github.com/GDG-Ukraine/gdg.org.ua/blob/master/vagga.yaml#L126-L129

**Comment by webknjaz** [comment]
Reopening this issue since you didn't complete whole task
